--- #YAML:1.0
name:                Astro-satpass
version:             0.012
abstract:            Classes and app to compute satellite visibility
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Date::Manip:                   1.14
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Tom Wyant (wyant at cpan dot org)
