---
name: Astro-satpass
version: 0.017
author:
  - Tom Wyant (wyant at cpan dot org)
abstract: Classes and app to compute satellite visibility
license: perl
resources:
  license: http://dev.perl.org/licenses/
dynamic_config: 1
provides:
  Astro::Coord::ECI:
    file: lib/Astro/Coord/ECI.pm
    version: 0.017
  Astro::Coord::ECI::Moon:
    file: lib/Astro/Coord/ECI/Moon.pm
    version: 0.004
  Astro::Coord::ECI::Star:
    file: lib/Astro/Coord/ECI/Star.pm
    version: 0.004
  Astro::Coord::ECI::Sun:
    file: lib/Astro/Coord/ECI/Sun.pm
    version: 0.006
  Astro::Coord::ECI::TLE:
    file: lib/Astro/Coord/ECI/TLE.pm
    version: 0.012
  Astro::Coord::ECI::TLE::Iridium:
    file: lib/Astro/Coord/ECI/TLE/Iridium.pm
    version: 0.005
  Astro::Coord::ECI::TLE::Set:
    file: lib/Astro/Coord/ECI/TLE/Set.pm
    version: 0.003
  Astro::Coord::ECI::Utils:
    file: lib/Astro/Coord/ECI/Utils.pm
    version: 0.009
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
