# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-satpass
version:      0.008
version_from: ECI.pm
installdirs:  site
requires:
    Date::Manip:                   1.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
