---
name: Astro-satpass
version: 0.025
author:
  - Tom Wyant (wyant at cpan dot org)
abstract: Classes and app to compute satellite visibility
license: perl
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Astro-satpass
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0.4
requires:
  Date::Manip: 1.14
  Params::Util: 0.25
  perl: 5.006
recommends:
  Time::y2038: 20081111
dynamic_config: 1
provides:
  Astro::Coord::ECI:
    file: lib/Astro/Coord/ECI.pm
    version: 0.025
  Astro::Coord::ECI::Moon:
    file: lib/Astro/Coord/ECI/Moon.pm
    version: 0.006
  Astro::Coord::ECI::Star:
    file: lib/Astro/Coord/ECI/Star.pm
    version: 0.006
  Astro::Coord::ECI::Sun:
    file: lib/Astro/Coord/ECI/Sun.pm
    version: 0.009
  Astro::Coord::ECI::TLE:
    file: lib/Astro/Coord/ECI/TLE.pm
    version: 0.019
  Astro::Coord::ECI::TLE::Iridium:
    file: lib/Astro/Coord/ECI/TLE/Iridium.pm
    version: 0.009
  Astro::Coord::ECI::TLE::Set:
    file: lib/Astro/Coord/ECI/TLE/Set.pm
    version: 0.008
  Astro::Coord::ECI::Utils:
    file: lib/Astro/Coord/ECI/Utils.pm
    version: 0.012
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
no_index:
  directory:
    - inc
    - t
